-   id: add-python-utf8-header
    name: Ensure Python UTF-8 header
    description: "Ensures all Python files start with '# -*- coding: utf-8 -*-'"
    entry: add_python_header.py
    language: script
    files: \.py$

-   id: add-js-odoo-header
    name: Ensure JS Odoo module header
    description: "Ensures all JS files start with '/** @odoo-module */'"
    entry: add_js_header.py
    language: script
    files: \.js$
